# -*- coding: utf-8 -*-
'''
Gatan Digital Micrograph DM4 file reader.
'''

import logging
from concurrent.futures import Future, ThreadPoolExecutor
from dataclasses import dataclass, field
from typing import Any

import numpy as np

logger = logging.getLogger('MRCZ')

# Executor for reading DM4 files in the background
_asyncExecutor = ThreadPoolExecutor(max_workers=1)

# Gatan tag type codes to NumPy dtypes. Unlisted codes give an empty string.
TAG_DTYPES = {
    2:  'int16',
    3:  'int32',
    4:  'uint16',
    5:  'uint32',
    6:  'float32',
    7:  'float64',
    8:  'bool',
    11: 'int64',
}


@dataclass(kw_only=True)
class DMImage:
    """
    This structure-like class is for storing 2D image or 3D image stack
    information, since Digital Micrograph likes to have more than one in a
    file.  Stores Calibrations, Data, and ImageTags.

    The NumPy array reference is stored in `imageData` and the meta-data is
    stored in a dictionary `imageInfo`.
    """
    imageInfo: dict = field(default_factory=dict) # Calibrations, tags, all in a dictionary
    shape: list = field(default_factory=list)     # necessary for unraveling
    imageData: np.ndarray = field(default_factory=lambda: np.zeros(1))


class readDM4:
    """
    A fast DM4 file reader to strip the data out of the large movie-mode files
    generated by K2 detectors along with important tags. Due to the emphasis on
    speed it's not a general file parser with dynamic allocation, so if Gatan
    changes the format a lot it will break the script.

    Parameters
    ----------
    filename
        path to the DM4 file to parse.
    verbose
        whether to emit debugging info on the ``'MRCZ'`` logger or not.

    Example
    -------

        dm4struct = readDM4( filename, verbose=False)

    dm4struct holds the (multiple) images in the DM4. Typically the zeroth image
    is the thumbnail. To convert to MRCZ::

        imageData = dm4struct.im[1].imageData

    is a NumPy array containing image intensities::

        imageInfo = dm4struct.im[1].imageInfo

    is a dict containing meta-data.

    Note
    ----

    Chris Boothroyd provides some information on the structure of .DM4 files here:

    http://www.er-c.org/cbb/info/dmformat/

    The directory structure of the file is tracked by passing the path of the
    parent to each tag parser. Gatan likes to have empty tag directories, so
    they are auto-numbered when present.

    One can examine file structure by setting ``verbose=True``, if you need to add
    some more tags to the dictionary generated by the parseTag function, for example.
    """

    def __init__(self, filename: str, verbose: bool = False):
        # Instatiate class fields
        self._unnamedIndices = np.zeros(20, dtype='int') # maximum number of nested tags
        self.im: list[DMImage] = [] # list of DMImage class objects
        self.verbose = verbose

        if verbose:
            logger.debug(f'Opening DM4 file: {filename}')

        with open(filename, 'rb') as f:
            self.f = f
            self._parseFile()
        self.f = None

        # Unravel images
        for mage in self.im:
            # FYI: Gatan stores image stacks [z,y,x] which is opposite to how they store the
            # dimensions (but is Numpy and C convention)
            mage.shape = np.array(mage.shape)[::-1]
            # This y-flip [:,::-1,...] puts us on the same origin-standard for data as MRC
            # Gatan uses a different standard for the origin location inside DM4 files.
            mage.imageData = np.reshape(mage.imageData, mage.shape, order='C')[:,::-1,...]
            # Image data is now compatible with MRCs saved in GMS, IMOD, EMAN2, etc.

    def _parseFile(self) -> None:
        """
        Walks the root tag directory. Split out of ``__init__`` so the handle
        can live in a ``with`` block and close even when parsing raises.
        """
        version = np.fromfile(self.f, dtype='>i4', count=1)[0]
        if version != 4:
            logger.warning('Only DM4 is supported, will probably crash spectacularly')
        np.fromfile(self.f, dtype='>i8', count=1)[0] # rootlen
        byteord = np.fromfile(self.f, dtype='>i4', count=1)[0] # 1 = little endian, generally always
        if byteord != 1:
            logger.error('Only little endian data ordering supported at present')
            return

        np.fromfile(self.f, dtype='i1', count=1)[0] # 1 = sorted
        np.fromfile(self.f, dtype='i1', count=1)[0] # 1 = open structure
        ntags_root = int(np.fromfile(self.f, dtype='>i8', count=1)[0]) # number of tags

        if self.verbose:
            logger.debug(f'DM version {version}, byte order {byteord}')
        # Now the tags start
        for J in range(ntags_root):

            # 20 = tag directory, 21 = tag base, 0 == EOF
            tag_type = np.fromfile(self.f, dtype='i1', count=1)[0]

            if tag_type == 20:

                loc_tagstart = self.f.tell()
                tag_namelen = np.fromfile(self.f, dtype='>i2', count=1)[0]

                if tag_namelen > 0:
                    tag_name = self.f.read(tag_namelen)
                else:
                    tag_name = b''

                tag_fieldlen = np.fromfile(self.f, dtype='>i8', count=1)[0]

                if tag_name == b'ImageList':
                    self.f.seek(loc_tagstart)
                    # So each image is an unnamed tag directory, composed of /ImageData and
                    # /ImageTags and /UniqueID
                    self.parseTagDir(b'/')
                    # We currently do not care about any tag but ImageList
                    break
                else:
                    # Go to next tag/tagdir
                    self.f.seek(self.f.tell() + tag_fieldlen)

            elif tag_type == 21:
                # throw away tags in root because we don't care for them
                self.discardTag()
            elif tag_type == 0:
                break # EOF

    def parseTag(self, parent: bytes) -> None:
        """ Parse a tag at the given file handle location """
        tag_namelen = np.fromfile(self.f, dtype='>i2', count=1)[0]

        if tag_namelen > 0:
            tag_name = self.f.read(tag_namelen)
        else:
            tag_name = b''

        tag_fieldlen = np.fromfile(self.f, dtype='>i8', count=1)[0]
        loc_tag = self.f.tell() # Save location so we can seek to end of tag later
        self.f.read(4) # Throw away %%%% seperator
        tag_ninfo = np.fromfile(self.f, dtype='>i8', count=1)[0]
        if self.verbose:
            logger.debug(f'Found tag: {parent}{tag_name} with {tag_ninfo} elements')

        split_tag_name = (parent + tag_name).split(b'/')

        # Skip ImageList

        imageIndex = int(split_tag_name[2].decode('ascii'))

        # Check to see if self.im[imageIndex] exists
        try:
            self.im[imageIndex]
        except IndexError:
            self.im.append(DMImage())

        if split_tag_name[3] == b'ImageData':
            if split_tag_name[4] == b'Calibrations':
                # No calibrations saved at present
                # /ImageList/1/ImageData/Calibrations/Brightness/Origin
                # /ImageList/1/ImageData/Calibrations/Brightness/Scale
                # /ImageList/1/ImageData/Calibrations/Brightness/Units
                # /ImageList/1/ImageData/Calibrations/Dimension/[0-2]/Origin
                # /ImageList/1/ImageData/Calibrations/Dimension/[0-2]/Scale
                # /ImageList/1/ImageData/Calibrations/Dimension/[0-2]/Units
                if split_tag_name[5] == b'Brightness':
                    if split_tag_name[6] == b'Origin':
                        self.im[imageIndex].imageInfo['IntensityOrigin'] = self.retrieveTagData(tag_ninfo)
                    elif split_tag_name[6] == b'Scale':
                        self.im[imageIndex].imageInfo['IntensityScale'] = self.retrieveTagData(tag_ninfo)
                    elif split_tag_name[6] == b'Units':
                        self.im[imageIndex].imageInfo['IntensityUnits'] = \
                            self.retrieveTagData(tag_ninfo).astype(np.uint8).tobytes().decode('utf-8')

                elif split_tag_name[5] == b'Dimension':
                    # 0 = x, 1 = y, 2 = z for split_tag_name[6]
                    dim_index = int(split_tag_name[6].decode('ascii'))
                    if dim_index == 0:
                        currDim = 'X'
                    elif dim_index == 1:
                        currDim = 'Y'
                    elif dim_index == 2:
                        currDim = 'Z'
                    else:
                        raise ValueError(f'DM4Import: Unknown dimension {split_tag_name[6]} '
                                         f'at location {hex(self.f.tell())}')

                    # Units is stored as uint16 array, which is actually unicode?
                    if split_tag_name[7] == b'Origin':
                        self.im[imageIndex].imageInfo['Dim'+currDim+'Origin'] = self.retrieveTagData(tag_ninfo)
                    elif split_tag_name[7] == b'Scale':
                        self.im[imageIndex].imageInfo['Dim'+currDim+'Scale'] = self.retrieveTagData(tag_ninfo)
                    elif split_tag_name[7] == b'Units':
                        # Sometimes we have wierd characters in the Units tag
                        raw_units = self.retrieveTagData(tag_ninfo).astype(np.int16).tobytes()
                        try:
                            self.im[imageIndex].imageInfo['Dim'+currDim+'Units'] = raw_units.decode('utf-8')
                        except UnicodeDecodeError:
                            try:
                                # "ISO-8859-1"
                                # 'windows-1252'
                                self.im[imageIndex].imageInfo['Dim'+currDim+'Units'] = \
                                    raw_units.decode('ISO-8859-1')
                            except UnicodeDecodeError:
                                pass

            elif split_tag_name[4] == b'Data':
                if self.verbose:
                    logger.debug(f'Found image {imageIndex} at offset : {self.f.tell()}')
                self.im[imageIndex].imageData = self.retrieveTagData(tag_ninfo)
            elif split_tag_name[4] == b'Dimensions':
                self.im[imageIndex].shape.append(self.retrieveTagData(tag_ninfo))

        elif split_tag_name[3] == b'ImageTags':

            if split_tag_name[4] == b'Acquisition':
                ### Find image flips ###
                # Here is where we can save any tags that we care for, like image rotations
                # /ImageList/1/ImageTags/Acquisition/Frame/Area/Transform/Transform List/0/Transpose/Horizontal Flip
                if split_tag_name[-1] == b'Horizontal Flip' and split_tag_name[-4] == b'Device':
                    # So annoyingly there are several of these tags, only some of which are the true flips.
                    self.im[imageIndex].imageInfo['HorzFlip'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[-1] == b'Vertical Flip' and split_tag_name[-4] == b'Device':
                    self.im[imageIndex].imageInfo['VertFlip'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[-1] == b'Diagonal Flip' and split_tag_name[-4] == b'Device':
                    self.im[imageIndex].imageInfo['DiagFlip'] = self.retrieveTagData(tag_ninfo)

                # Pixel size seems to be complex, not sure if I'm retrieving it correctly
                # (only important for non-square pixel detectors)
                elif split_tag_name[-1] == b'Pixel Size (um)' and split_tag_name[-3] == b'Device':
                    self.im[imageIndex].imageInfo['DetectorPixelSize'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[-1] == b'Exposure' and split_tag_name[-2] == b'Detector':
                    self.im[imageIndex].imageInfo['Exposure'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[-1] == b'hbin' and split_tag_name[-2] == b'Detector':
                    self.im[imageIndex].imageInfo['HorzBin'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[-1] == b'vbin' and split_tag_name[-2] == b'Detector':
                    self.im[imageIndex].imageInfo['VertBin'] = self.retrieveTagData(tag_ninfo)

            elif split_tag_name[4] == b'Calibration':

                if split_tag_name[5] == b'Dose Rate':
                    if split_tag_name[6] == b'Calibration':
                        if 'DoseRateCalibration' not in self.im[imageIndex].imageInfo:
                            self.im[imageIndex].imageInfo['DoseRateCalibration'] = []

                        try:
                            self.im[imageIndex].imageInfo['DoseRateCalibration'].append(
                                self.retrieveTagData(tag_ninfo))
                        except (IndexError, ValueError, TypeError):
                            logger.warning('Failed to import DoseRateCalibration')

            elif split_tag_name[4] == b'Microscope Info':
                if split_tag_name[5] == b'Actual Magnification':
                    self.im[imageIndex].imageInfo['ActualMag'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Indicated Magnification':
                    self.im[imageIndex].imageInfo['NominalMag'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Cs(mm)':
                    self.im[imageIndex].imageInfo['C3'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Voltage':
                    self.im[imageIndex].imageInfo['Voltage'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Mode':
                    self.im[imageIndex].imageInfo['MicroscopeMode'] = \
                        self.retrieveTagData(tag_ninfo).astype(np.uint8).tobytes().decode('ascii')
            elif split_tag_name[4] == b'EELS Spectrometer':
                if split_tag_name[5] == b'Aperture index':
                    self.im[imageIndex].imageInfo['EELSApertureIndex'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Aperture label':
                    self.im[imageIndex].imageInfo['EELSApertureLabel'] = \
                        self.retrieveTagData(tag_ninfo).astype(np.uint8).tobytes().decode('ascii')
                elif split_tag_name[5] == b'Energy loss (eV)':
                    self.im[imageIndex].imageInfo['EELSEnergyLoss'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Slit inserted':
                    self.im[imageIndex].imageInfo['EELSSlitIn'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Slit width (eV)':
                    self.im[imageIndex].imageInfo['EELSSlitWidth'] = self.retrieveTagData(tag_ninfo)
            elif split_tag_name[4] == b'Latitude-S':
                if split_tag_name[5] == b'Distance To Focus Position':
                    self.im[imageIndex].imageInfo['LatSDistanceToFocus'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Intended Defocus':
                    self.im[imageIndex].imageInfo['LatSIntendedDefocus'] = self.retrieveTagData(tag_ninfo)
                elif split_tag_name[5] == b'Beam Diameter (nm)':
                    self.im[imageIndex].imageInfo['LatSBeamDiameter'] = self.retrieveTagData(tag_ninfo)
        # Go to next location
        self.f.seek(loc_tag + tag_fieldlen)

    def getTagDType(self, bytecode: int) -> str:
        """ Returns the NumPy dtype name for a Gatan tag type code, '' if unknown. """
        return TAG_DTYPES.get(int(bytecode), '')

    def retrieveTagData(self, tag_ninfo: int) -> Any:
        """ Get the actual data from the tag, which is then stored in one of the dicts or imageData """
        # Here is basically where we should check tag_name to see if it's important...
        tag_loc = self.f.tell()
        tag_infos = np.fromfile(self.f, dtype='>i8', count=tag_ninfo)
        for K in range(tag_infos.size):
            if tag_infos[K] == 15: # struct
                # Structs are organized really strangely in the file, they are essentially in the
                # tag header so our reading doesn't work properly with them. In essence we need to
                # go back to where we think the struct should be.
                self.f.seek(tag_loc + 8*K + 16)
                struct_fieldcount = int(np.fromfile(self.f, dtype='>i8', count=1)[0])
                struct_fielddtype = []
                struct_fieldval = []
                for J in range(struct_fieldcount):
                    np.fromfile(self.f, dtype='>i8', count=1) # Zero
                    struct_fielddtype.append(
                        self.getTagDType(np.fromfile(self.f, dtype='>i8', count=1)[0]))
                for J in range(struct_fieldcount):
                    struct_fieldval.append(
                        np.fromfile(self.f, dtype=struct_fielddtype[J], count=1)[0])
                return struct_fieldval
            elif tag_infos[K] == 20: # array
                if self.verbose:
                    logger.debug('Found array')
                try:
                    K += 1 # Warning: sometimes arrays are empty
                    array_dtype = self.getTagDType(tag_infos[K])
                    K += 1
                    array_ncount = int(tag_infos[K])
                    if self.verbose:
                        logger.debug(f'Array dtype: {array_dtype}, array ncount: {array_ncount}')
                    if array_ncount > 0:
                        return np.fromfile(self.f, dtype=array_dtype, count=array_ncount)
                except IndexError:
                    pass
            elif tag_infos[K] == 9: # string
                tag_char = self.f.read(1)
                if self.verbose:
                    logger.debug(f'Found char: {tag_char}')
            elif tag_infos[K] == 18: # string
                if self.verbose:
                    logger.debug('FIXME Found string')
            else: # singleton
                tag_dtype = self.getTagDType(tag_infos[K])
                if tag_dtype != '':
                    tag_data = np.fromfile(self.f, dtype=tag_dtype, count=1)[0]
                    if self.verbose:
                        logger.debug(f'Singleton: {tag_dtype}: {tag_data}')
                    return tag_data
        return None

    def discardTag(self) -> None:
        """ Quickly parse to the end of tag that we don't care about its information """
        tag_namelen = np.fromfile(self.f, dtype='>i2', count=1)[0]
        self.f.seek(self.f.tell() + tag_namelen)
        tag_fieldlen = np.fromfile(self.f, dtype='>i8', count=1)[0]
        self.f.seek(self.f.tell() + tag_fieldlen)

    def parseTagDir(self, parent: bytes) -> None:
        """ Parse a tag directory at the given file handle location """
        try:
            tag_namelen = np.fromfile(self.f, dtype='>i2', count=1)[0]

            if tag_namelen > 0:
                tag_name = self.f.read(tag_namelen)
            else:
                tag_name = b''

            tag_fieldlen = np.fromfile(self.f, dtype='>i8', count=1)[0]

        except IndexError:
            if self.verbose:
                logger.debug('Caught IndexError, trying to recover position in file')
            return

        # Handle empty tag_name by giving it an auto-generated number
        if not tag_name:
            if self.verbose:
                logger.debug('Found empty tag')
            tag_depth = int(parent.count(b'/') - 1)

            tag_name = str(self._unnamedIndices[tag_depth]).encode('ascii')
            self._unnamedIndices[tag_depth] += 1
            # Reset all higher indices
            self._unnamedIndices[tag_depth+1:] = 0
        loc_tagdir = self.f.tell()
        self.f.read(2) # Throw away sorted and closed
        ntags_dir = int(np.fromfile(self.f, dtype='>i8', count=1)[0])
        if self.verbose:
            logger.debug(f'Found tag dir {parent}{tag_name} with {ntags_dir} tags')

        # So typically ImageList has two empty name tag directories, of which one is various stuff
        # and the other is the data
        for I in range(ntags_dir):
            try:
                # 20 = tag directory, 21 = tag base, 0 == EOF
                subtag_type = np.fromfile(self.f, dtype='i1', count=1)[0]
            except IndexError:
                if self.verbose:
                    logger.debug('Caught IndexError, trying to recover')
                break
            if subtag_type == 20:
                self.parseTagDir(parent + tag_name + b'/')
            elif subtag_type == 21:
                self.parseTag(parent + tag_name + b'/')
            elif subtag_type == 0:
                break # EOF
        # Go to next tag in root directory
        self.f.seek(loc_tagdir + tag_fieldlen)


def asyncReadDM4(*args, **kwargs) -> Future:
    '''
    Calls `readDM4` in a separate thread and executes it in the background.

    Parameters
    ----------
    Valid arguments are as for `readDM4()`.

    Returns
    -------
    future
        A ``concurrent.futures.Future()`` object.  Calling ``future.result()``
        will halt until the read is finished and returns the parsed `readDM4`
        object.

    Example
    -------

        worker = asyncReadDM4( 'someones_file.dm4' )
        # Do some work
        dm4struct = worker.result()
    '''
    return _asyncExecutor.submit(readDM4, *args, **kwargs)


# snake_case aliases for the public API, bound to the same objects so the
# original names remain fully supported.
read_dm4 = readDM4
async_read_dm4 = asyncReadDM4
