[build-system]
requires = [
    'setuptools',
    'build',
    'wheel',
    'numpy', 
    "setuptools-scm"]

build-backend = "setuptools.build_meta"


[project]
name = "mrcz"
readme = "README.rst"
# Set version via 
# git tag vX.Y.Z
# git push origin
# git push origin --tags
dynamic = ["version"]
description = "MRCZ meta-compressed image file-format library"
authors = [{name = "Robert A. McLeod", email = "robbmcleod@gmail.com"}]
license = 'BSD-3-Clause'
requires-python = ">=3.11"
dependencies = [
    "numpy"
    ]
[tool.setuptools]
packages = ["mrcz"]

[tool.setuptools_scm]
write_to = "mrcz/__version__.py"
# Force simple x.y.z version output
version_scheme = "only-version"
local_scheme = "no-local-version"